version: '3'
services:
  frontend-container:
    image: frontend
    ports:
      - 3000-3004:80
    depends_on:
      - backend-container
    environment:
      - CONTAINER_URL=${CONTAINER_NAME}
      - API_URL=/api
    networks:
      - hospital
  backend-container:
    image: backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://${CONTAINER_NAME}_sql:3306/HospitalSystem?createDatabaseIfNotExist=true&useSSL=false
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_CLOUD_VAULT_HOST=vault
      - hospitalName=${CONTAINER_NAME}
      - VAULT_TOKEN=${VAULT_TOKEN}
    depends_on:
      - mysql-container
    restart: on-failure
    container_name: ${CONTAINER_NAME}
    networks:
      - hospital
  mysql-container:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - hospital
    container_name: ${CONTAINER_NAME}_sql
volumes:
  db_data:

networks:
  hospital:
    external: true